export const contact_translations: any = {
    '🇨🇦 EN': {
        contactTitle: "Contact Us",
        contactSubtitle: "Get in touch with our professional team for commercial cleaning solutions.",
        formLabels: {
            name: "Name",
            email: "Email",
            phone: "Phone",
            message: "Message",
        },
        formPlaceholders: {
            name: "Your Name",
            email: "Your Email",
            phone: "Phone",
            message: "Your Message",
        },
        formErrors: {
            name: "Name is required",
            email: "Email is required",
            phone: "Phone",
            message: "Message is required",
        },
        submitButton: "Send Message",
        submittingButton: "Sending...",
        getInTouch: "Get in Touch",
        contactInfo: {
            phone: "+1 (514) 296-4595",
            email: "contact@ecoserv.ca",
            address: "739 rue Roberge, Sherbrooke, QC",
        },
        successMessage: "Thank you for contacting us! We'll get back to you soon.",
    },
    '⚜️ FR': {
        contactTitle: "Contactez-nous",
        contactSubtitle: "Contactez notre équipe professionnelle pour des solutions de nettoyage commercial.",
        formLabels: {
            name: "Nom",
            email: "Email",
            phone: "Téléphone",
            message: "Message",
        },
        formPlaceholders: {
            name: "Votre nom",
            email: "Votre email",
            phone: "Téléphone",
            message: "Votre message",
        },
        formErrors: {
            name: "Le nom est requis",
            email: "L'email est requis",
            phone: "Téléphone",
            message: "Le message est requis",
        },
        submitButton: "Envoyer le message",
        submittingButton: "Envoi en cours...",
        getInTouch: "Contactez-nous",
        contactInfo: {
            phone: "+1 (514) 296-4595",
            email: "contact@ecoserv.ca",
            address: "739 rue Roberge, Sherbrooke, QC",
        },
        successMessage: "Merci de nous avoir contactés! Nous vous répondrons bientôt.",
    },
    '🇨🇱 ES': {
        contactTitle: "Contáctenos",
        contactSubtitle: "Póngase en contacto con nuestro equipo profesional para soluciones de limpieza comercial.",
        formLabels: {
            name: "Nombre",
            email: "Correo electrónico",
            phone: "Teléfono",
            message: "Mensaje",
        },
        formPlaceholders: {
            name: "Su nombre",
            email: "Su correo electrónico",
            phone: "Teléfono",
            message: "Su mensaje",
        },
        formErrors: {
            name: "El nombre es obligatorio",
            email: "El correo electrónico es obligatorio",
            phone: "Teléfono",
            message: "El mensaje es obligatorio",
        },
        submitButton: "Enviar mensaje",
        submittingButton: "Enviando...",
        getInTouch: "Contáctenos",
        contactInfo: {
            phone: "+1 (514) 296-4595",
            email: "contact@ecoserv.ca",
            address: "739 rue Roberge, Sherbrooke, QC",
        },
        successMessage: "¡Gracias por contactarnos! Nos pondremos en contacto con usted pronto.",
    },
};